# -*- coding: utf-8 -*-
"""
O conteúdo do índice de utilização — `site/api.html` e `site/en/api.html`.

DOCUMENTO DE MANUTENÇÃO.

Por que existe
--------------
As duas páginas eram escritas à mão, uma de cada lado, e nada ligava uma à
outra: 14 seções, 59 linhas de tabela e 13 janelas de código **repetidas** em
dois arquivos de 455 linhas. Corrigir um exemplo pedia lembrar do gêmeo, e
esquecer não quebrava nada -- foi assim que a referência da API divergiu antes
de passar a ser gerada.

Aqui cada texto é um par `(português, inglês)` e as duas páginas saem do mesmo
material. O gerador recusa seção com quantidade de blocos diferente entre as
línguas, e recusa janela cujo **código** deixe de ser o mesmo depois de tirar
comentário e literal de texto: é o que pega "mudei o exemplo em PT e esqueci o
EN".

Isto **não** sai da spec, e não deveria mesmo: é material editorial, escrito
para ensinar, com assinatura informal (`Cell(w,h,txt,borda,ln,...)`) e exemplo
montado à mão. A referência exata, gerada do Javadoc, é a outra página.

Cada seção tem `id`, número, título, o rótulo `curto` do índice do topo, e
`blocos` na ordem em que saem: `desc` (parágrafo de abertura), `tabela`
(API / o que faz), `nota` (parágrafo destacado) e `janela` (exemplo de código,
com o nome do arquivo da barra de título).
"""

# a nota do topo, sobre notação posicional e nomeada
NOTA_TOPO = ("<b>Como passar parâmetros:</b> toda API aceita notação posicional\n  (<code>Cell(0, 10, 'Olá', '1', 1, 'C')</code>) ou nomeada\n  (<code>Cell(pw =&gt; 0, ph =&gt; 10, ptxt =&gt; 'Olá', palign =&gt; 'C')</code>) — a nomeada é a\n  recomendada. Parâmetros com <i>default</i> podem ser omitidos; medidas usam a unidade do\n  <code>Init</code>; cores são RGB 0–255; faixas de páginas aceitam <code>'ALL'</code> ou\n  <code>'1,3-5,21-'</code>; opções extras viajam em <code>JSON_OBJECT_T</code>.",
             "<b>How to pass parameters:</b> every API accepts positional notation\n  (<code>Cell(0, 10, 'Hello', '1', 1, 'C')</code>) or named\n  (<code>Cell(pw =&gt; 0, ph =&gt; 10, ptxt =&gt; 'Hello', palign =&gt; 'C')</code>) — named is the\n  recommended one. Parameters with a <i>default</i> may be omitted; measurements use the unit\n  given to <code>Init</code>; colours are RGB 0–255; page ranges accept <code>'ALL'</code> or\n  <code>'1,3-5,21-'</code>; extra options travel in a <code>JSON_OBJECT_T</code>.")

SECOES = [
    {
        'id': "init", 'n': "01",
        'titulo': ("Ciclo de vida", "Life cycle"),
        'curto': ("Ciclo de vida", "Life cycle"),
        'blocos': [
            ("desc",
             "Todo documento começa com <code>Init</code>; o estado vive na sessão (package-only).",
             "Every document starts with <code>Init</code>; the state lives in the session (package-only)."),
            ('tabela', [
                (("Init(orient, unit, format, encoding)",
                  "Init(orient, unit, format, encoding)"),
                 ("Inicia documento: 'P'/'L' · mm/cm/pt/in · A3/A4/A5/Letter/Legal · UTF-8",
                  "Starts a document: 'P'/'L' · mm/cm/pt/in · A3/A4/A5/Letter/Legal · UTF-8")),
                (("Reset",
                  "Reset"),
                 ("Zera o estado e libera CLOBs temporários",
                  "Clears the state and frees temporary CLOBs")),
                (("IsInitialized",
                  "IsInitialized"),
                 ("TRUE se há documento em andamento",
                  "TRUE if a document is in progress")),
                (("co_version",
                  "co_version"),
                 ("Constante com a versão instalada",
                  "Constant holding the installed version")),
            ]),
            ('janela', ("hello.sql", "hello.sql"), [
                "DECLARE l_pdf BLOB;",
                "BEGIN",
                "  PL_FPDF.Init(",
                "    p_orientation => 'P',     -- 'P' retrato | 'L' paisagem",
                "    p_unit        => 'mm',    -- 'mm' | 'cm' | 'pt' | 'in'",
                "    p_format      => 'A4');   -- 'A4' | 'A3' | 'A5' | 'Letter' | 'Legal'",
                "  PL_FPDF.AddPage();",
                "  PL_FPDF.SetFont('Arial', 'B', 16);  -- família, estilo ''/B/I/BI/U, tamanho pt",
                "  PL_FPDF.Cell(0, 10, 'Olá, Mundo!', '0', 1, 'C');",
                "  l_pdf := PL_FPDF.OutputBlob();",
                "END;",
            ], [
                "DECLARE l_pdf BLOB;",
                "BEGIN",
                "  PL_FPDF.Init(",
                "    p_orientation => 'P',     -- 'P' portrait | 'L' landscape",
                "    p_unit        => 'mm',    -- 'mm' | 'cm' | 'pt' | 'in'",
                "    p_format      => 'A4');   -- 'A4' | 'A3' | 'A5' | 'Letter' | 'Legal'",
                "  PL_FPDF.AddPage();",
                "  PL_FPDF.SetFont('Arial', 'B', 16);  -- family, style ''/B/I/BI/U, size in pt",
                "  PL_FPDF.Cell(0, 10, 'Hello, World!', '0', 1, 'C');",
                "  l_pdf := PL_FPDF.OutputBlob();",
                "END;",
            ]),
        ],
    },
    {
        'id': "paginas", 'n': "02",
        'titulo': ("Páginas e posicionamento", "Pages and positioning"),
        'curto': ("Páginas e posição", "Pages and position"),
        'blocos': [
            ('tabela', [
                (("AddPage(orient, format, rotation)",
                  "AddPage(orient, format, rotation)"),
                 ("Nova página; NULL herda do Init; rotação 0/90/180/270",
                  "New page; NULL inherits from Init; rotation 0/90/180/270")),
                (("SetPage(n) · GetCurrentPage · PageNo",
                  "SetPage(n) · GetCurrentPage · PageNo"),
                 ("Voltar a uma página existente · página ativa · nº corrente",
                  "Go back to an existing page · active page · current number")),
                (("SetMargins(l,t,r) e variantes",
                  "SetMargins(l,t,r) and variants"),
                 ("Margens (SetLeftMargin / SetTopMargin / SetRightMargin)",
                  "Margins (SetLeftMargin / SetTopMargin / SetRightMargin)")),
                (("SetAutoPageBreak(auto, margem)",
                  "SetAutoPageBreak(auto, margin)"),
                 ("Quebra automática ao atingir a margem inferior",
                  "Automatic break on reaching the bottom margin")),
                (("Ln(h) · GetX/SetX · GetY/SetY · SetXY",
                  "Ln(h) · GetX/SetX · GetY/SetY · SetXY"),
                 ("Controle do cursor de escrita",
                  "Control of the writing cursor")),
            ]),
            ('janela', ("paginas.sql", "pages.sql"), [
                "PL_FPDF.SetMargins(left => 20, top => 15, right => 20);  -- right omitido = igual à esquerda",
                "PL_FPDF.SetAutoPageBreak(pauto => TRUE, pMargin => 15);    -- quebra a 15mm do fim",
                "PL_FPDF.AddPage(p_orientation => 'L');                     -- só o que muda; resto herda do Init",
                "PL_FPDF.SetXY(x => 20, y => 40);                           -- cursor na unidade do documento",
            ], [
                "PL_FPDF.SetMargins(left => 20, top => 15, right => 20);  -- right omitted = same as left",
                "PL_FPDF.SetAutoPageBreak(pauto => TRUE, pMargin => 15);    -- breaks 15mm from the bottom",
                "PL_FPDF.AddPage(p_orientation => 'L');                     -- only what changes; the rest inherits from Init",
                "PL_FPDF.SetXY(x => 20, y => 40);                           -- cursor in the document unit",
            ]),
        ],
    },
    {
        'id': "fontes", 'n': "03",
        'titulo': ("Fontes e UTF-8", "Fonts and UTF-8"),
        'curto': ("Fontes e UTF-8", "Fonts and UTF-8"),
        'blocos': [
            ('tabela', [
                (("SetFont(família, estilo, tamanho)",
                  "SetFont(family, style, size)"),
                 ("Core: Arial/Helvetica, Times, Courier · estilos '', B, I, BI, U",
                  "Core: Arial/Helvetica, Times, Courier · styles '', B, I, BI, U")),
                (("SetFontSize(pt)",
                  "SetFontSize(pt)"),
                 ("Muda apenas o tamanho",
                  "Changes the size only")),
                (("AddTTFFont(nome, blob, enc, embed)",
                  "AddTTFFont(name, blob, enc, embed)"),
                 ("TrueType a partir de BLOB, com embedding",
                  "TrueType from a BLOB, with embedding")),
                (("LoadTTFFromFile(nome, arquivo, directory)",
                  "LoadTTFFromFile(name, file, directory)"),
                 ("TrueType de um DIRECTORY Oracle",
                  "TrueType from an Oracle DIRECTORY")),
                (("IsTTFFontLoaded · GetTTFFontInfo · ClearTTFFontCache",
                  "IsTTFFontLoaded · GetTTFFontInfo · ClearTTFFontCache"),
                 ("Gestão do cache de fontes",
                  "Font cache management")),
            ]),
        ],
    },
    {
        'id': "texto", 'n': "04",
        'titulo': ("Escrita de texto", "Writing text"),
        'curto': ("Escrita de texto", "Writing text"),
        'blocos': [
            ('tabela', [
                (("Cell(w,h,txt,borda,ln,alinh,fill,link)",
                  "Cell(w,h,txt,border,ln,align,fill,link)"),
                 ("Bloco retangular — a API mais usada",
                  "Rectangular block — the most used API")),
                (("MultiCell(w,h,txt,borda,alinh,fill)",
                  "MultiCell(w,h,txt,border,align,fill)"),
                 ("Parágrafo com quebra automática (function retorna nº de linhas)",
                  "Paragraph with automatic wrapping (the function returns the line count)")),
                (("Write(h, txt, link)",
                  "Write(h, txt, link)"),
                 ("Texto fluido inline (misture fontes no meio da frase)",
                  "Inline flowing text (mix fonts mid-sentence)")),
                (("Text(x, y, txt)",
                  "Text(x, y, txt)"),
                 ("Posição absoluta, sem mover o cursor",
                  "Absolute position, without moving the cursor")),
                (("CellRotated(...) · WriteRotated(...)",
                  "CellRotated(...) · WriteRotated(...)"),
                 ("Texto rotacionado 0/90/180/270",
                  "Text rotated 0/90/180/270")),
                (("GetStringWidth(txt) · SetLineSpacing",
                  "GetStringWidth(txt) · SetLineSpacing"),
                 ("Medição para centralizar · espaçamento entre linhas",
                  "Measuring in order to centre · line spacing")),
            ]),
            ('janela', ("cell_parametros.sql", "cell_parameters.sql"), [
                "PL_FPDF.Cell(",
                "  pw      => 0,        -- largura; 0 = até a margem direita",
                "  ph      => 10,       -- altura da célula",
                "  ptxt    => 'Total: R$ 1.234,56',",
                "  pborder => 'LTB',    -- '0' | '1' | combinação de L,T,R,B",
                "  pln     => 1,        -- 0 cursor à direita | 1 próxima linha | 2 abaixo",
                "  palign  => 'R',      -- 'L' | 'C' | 'R'",
                "  pfill   => 1,        -- 1 = fundo com a cor de SetFillColor",
                "  plink   => '');      -- URL ou link interno (AddLink)",
                "",
                "l_linhas := PL_FPDF.MultiCell(0, 6, l_paragrafo, '1', 'J');  -- 'J' justificado; retorna nº de linhas",
                "PL_FPDF.CellRotated(40, 10, 'VERTICAL', p_rotation => 90);   -- 0/90/180/270",
            ], [
                "PL_FPDF.Cell(",
                "  pw      => 0,        -- width; 0 = up to the right margin",
                "  ph      => 10,       -- cell height",
                "  ptxt    => 'Total: 1,234.56',",
                "  pborder => 'LTB',    -- '0' | '1' | any combination of L,T,R,B",
                "  pln     => 1,        -- 0 cursor to the right | 1 next line | 2 below",
                "  palign  => 'R',      -- 'L' | 'C' | 'R'",
                "  pfill   => 1,        -- 1 = background in the SetFillColor colour",
                "  plink   => '');      -- URL or internal link (AddLink)",
                "",
                "l_lines := PL_FPDF.MultiCell(0, 6, l_paragraph, '1', 'J');  -- 'J' justified; returns the line count",
                "PL_FPDF.CellRotated(40, 10, 'VERTICAL', p_rotation => 90);   -- 0/90/180/270",
            ]),
        ],
    },
    {
        'id': "desenho", 'n': "05",
        'titulo': ("Cores e desenho", "Colours and drawing"),
        'curto': ("Cores e desenho", "Colours and drawing"),
        'blocos': [
            ('tabela', [
                (("SetDrawColor / SetFillColor / SetTextColor (r,g,b)",
                  "SetDrawColor / SetFillColor / SetTextColor (r,g,b)"),
                 ("Cores RGB 0–255 de contorno, preenchimento e texto",
                  "RGB 0–255 colours for stroke, fill and text")),
                (("SetLineWidth · SetDash · SetLineDashPattern",
                  "SetLineWidth · SetDash · SetLineDashPattern"),
                 ("Espessura e tracejado",
                  "Thickness and dashes")),
                (("Line(x1,y1,x2,y2) · Rect(x,y,w,h,estilo)",
                  "Line(x1,y1,x2,y2) · Rect(x,y,w,h,style)"),
                 ("Linha · retângulo ('' contorno, 'F' cheio, 'DF' ambos)",
                  "Line · rectangle ('' outline, 'F' filled, 'DF' both)")),
                (("Poly(pontos, fechar, estilo) · Triangle(...)",
                  "Poly(points, close, style) · Triangle(...)"),
                 ("Polígonos e triângulos",
                  "Polygons and triangles")),
            ]),
            ('janela', ("desenho.sql", "drawing.sql"), [
                "PL_FPDF.SetDrawColor(r => 200, g => 0, b => 0);   -- RGB 0-255; só r = tom de cinza",
                "PL_FPDF.SetFillColor(240, 240, 240);",
                "PL_FPDF.SetLineWidth(0.5);                          -- na unidade do documento",
                "PL_FPDF.Rect(px => 10, py => 40, pw => 60, ph => 25, pstyle => 'DF');  -- '' contorno | 'F' cheio | 'DF' ambos",
                "PL_FPDF.SetLineDashPattern('[3 2] 0');              -- 3 on, 2 off (pontos PDF)",
            ], [
                "PL_FPDF.SetDrawColor(r => 200, g => 0, b => 0);   -- RGB 0-255; r alone = shade of grey",
                "PL_FPDF.SetFillColor(240, 240, 240);",
                "PL_FPDF.SetLineWidth(0.5);                          -- in the document unit",
                "PL_FPDF.Rect(px => 10, py => 40, pw => 60, ph => 25, pstyle => 'DF');  -- '' outline | 'F' filled | 'DF' both",
                "PL_FPDF.SetLineDashPattern('[3 2] 0');              -- 3 on, 2 off (PDF points)",
            ]),
        ],
    },
    {
        'id': "imagens", 'n': "06",
        'titulo': ("Imagens e links", "Images and links"),
        'curto': ("Imagens e links", "Images and links"),
        'blocos': [
            ('tabela', [
                (("Image(arquivo, x, y, w, h, tipo, link)",
                  "Image(file, x, y, w, h, type, link)"),
                 ("PNG/JPEG; w ou h = 0 mantém proporção",
                  "PNG/JPEG; w or h = 0 keeps the aspect ratio")),
                (("getImageFromUrl(url)",
                  "getImageFromUrl(url)"),
                 ("Baixa imagem via UTL_HTTP para usar no documento",
                  "Downloads an image via UTL_HTTP to use in the document")),
                (("AddLink · SetLink(link, y, página)",
                  "AddLink · SetLink(link, y, page)"),
                 ("Links internos (índices, sumários)",
                  "Internal links (indexes, tables of contents)")),
                (("Link(x,y,w,h,url)",
                  "Link(x,y,w,h,url)"),
                 ("Área clicável arbitrária",
                  "An arbitrary clickable area")),
            ]),
            ('janela', ("imagem.sql", "image.sql"), [
                "PL_FPDF.Image(",
                "  pFile   => 'logo.png',  -- arquivo no DIRECTORY",
                "  pX      => 10, pY => 10,",
                "  pWidth  => 40,          -- largura fixa…",
                "  pHeight => 0,           -- …0 = altura proporcional",
                "  pType   => NULL,        -- NULL autodetecta PNG/JPEG",
                "  pLink   => 'https://msbrasil.inf.br');  -- imagem clicável (opcional)",
            ], [
                "PL_FPDF.Image(",
                "  pFile   => 'logo.png',  -- file in the DIRECTORY",
                "  pX      => 10, pY => 10,",
                "  pWidth  => 40,          -- fixed width…",
                "  pHeight => 0,           -- …0 = proportional height",
                "  pType   => NULL,        -- NULL auto-detects PNG/JPEG",
                "  pLink   => 'https://msbrasil.inf.br');  -- clickable image (optional)",
            ]),
        ],
    },
    {
        'id': "headers", 'n': "07",
        'titulo': ("Cabeçalho e rodapé automáticos", "Automatic header and footer"),
        'curto': ("Cabeçalho/rodapé", "Header/footer"),
        'blocos': [
            ("desc",
             "Registre procedures suas para executarem a cada página, com parâmetros.",
             "Register procedures of your own to run on every page, with parameters."),
            ('tabela', [
                (("SetHeaderProc(proc, params)",
                  "SetHeaderProc(proc, params)"),
                 ("Procedure chamada no topo de cada página",
                  "Procedure called at the top of every page")),
                (("SetFooterProc(proc, params)",
                  "SetFooterProc(proc, params)"),
                 ("Procedure chamada no rodapé",
                  "Procedure called in the footer")),
                (("SetAliasNbPages('{nb}')",
                  "SetAliasNbPages('{nb}')"),
                 ("Placeholder do total de páginas (\"Página 2/{nb}\")",
                  "Placeholder for the page total (\"Page 2/{nb}\")")),
            ]),
            ('janela', ("rodape.sql", "footer.sql"), [
                "-- procedure sua, chamada a cada página:",
                "PL_FPDF.SetFooterProc(footerprocname => 'meu_pkg.meu_footer');",
                "-- com parâmetros: tv4000a é associative array indexado pelo NOME do parâmetro",
                "--   l_p PL_FPDF.tv4000a;  (não existe construtor tv4000a(...))",
                "l_p('p_titulo')  := 'Relatório Mensal';",
                "l_p('p_periodo') := 'Ago/2026';",
                "PL_FPDF.SetHeaderProc(",
                "  headerprocname => 'meu_pkg.meu_header',",
                "  paramTable     => l_p);",
                "PL_FPDF.SetAliasNbPages('{nb}');  -- use '{nb}' no texto = total de páginas",
            ], [
                "-- a procedure of yours, called on every page:",
                "PL_FPDF.SetFooterProc(footerprocname => 'my_pkg.my_footer');",
                "-- with parameters: tv4000a is an associative array indexed by the parameter NAME",
                "--   l_p PL_FPDF.tv4000a;  (there is no tv4000a(...) constructor)",
                "l_p('p_title')  := 'Monthly Report';",
                "l_p('p_period') := 'Aug/2026';",
                "PL_FPDF.SetHeaderProc(",
                "  headerprocname => 'my_pkg.my_header',",
                "  paramTable     => l_p);",
                "PL_FPDF.SetAliasNbPages('{nb}');  -- use '{nb}' in the text = total pages",
            ]),
        ],
    },
    {
        'id': "codigos", 'n': "08",
        'titulo': ("QR Code e código de barras", "QR Code and barcode"),
        'curto': ("QR e barras", "QR and barcodes"),
        'blocos': [
            ('tabela', [
                (("AddQRCode(x, y, size, dados, formato, correção)",
                  "AddQRCode(x, y, size, data, format, correction)"),
                 ("Formatos TEXT, URL, PIX, VCARD, WIFI, EMAIL · correção L/M/Q/H",
                  "Formats TEXT, URL, PIX, VCARD, WIFI, EMAIL · correction L/M/Q/H")),
                (("AddBarcode(x, y, w, h, código, tipo, texto)",
                  "AddBarcode(x, y, w, h, code, type, text)"),
                 ("CODE128, CODE39, EAN13, EAN8, ITF14",
                  "CODE128, CODE39, EAN13, EAN8, ITF14")),
            ]),
            ("nota",
             "PIX com payload EMV completo e Boleto FEBRABAN prontos para uso estão na\n  <a href=\"https://github.com/Maxwbh/pl_fpdf/tree/master/extensions/brazilian-payments\">extensão brazilian-payments</a>.",
             "PIX with a full EMV payload and FEBRABAN Boleto, ready to use, live in the\n  <a href=\"https://github.com/Maxwbh/pl_fpdf/tree/master/extensions/brazilian-payments\">brazilian-payments extension</a> — both are Brazilian payment standards."),
            ('janela', ("qr_barras.sql", "qr_barcode.sql"), [
                "PL_FPDF.AddQRCode(",
                "  p_x => 150, p_y => 20, p_size => 40,   -- posição e lado (unidade do doc)",
                "  p_data             => 'https://msbrasil.inf.br',",
                "  p_format           => 'URL',          -- TEXT | URL | PIX | VCARD | WIFI | EMAIL",
                "  p_error_correction => 'M');           -- L 7% | M 15% | Q 25% | H 30%",
                "",
                "PL_FPDF.AddBarcode(",
                "  p_x => 30, p_y => 70, p_width => 150, p_height => 20,",
                "  p_code      => '7891234567895',",
                "  p_type      => 'EAN13',               -- CODE128 | CODE39 | EAN13 | EAN8 | ITF14",
                "  p_show_text => TRUE);                 -- número legível abaixo das barras",
            ], [
                "PL_FPDF.AddQRCode(",
                "  p_x => 150, p_y => 20, p_size => 40,   -- position and side (document unit)",
                "  p_data             => 'https://msbrasil.inf.br',",
                "  p_format           => 'URL',          -- TEXT | URL | PIX | VCARD | WIFI | EMAIL",
                "  p_error_correction => 'M');           -- L 7% | M 15% | Q 25% | H 30%",
                "",
                "PL_FPDF.AddBarcode(",
                "  p_x => 30, p_y => 70, p_width => 150, p_height => 20,",
                "  p_code      => '7891234567895',",
                "  p_type      => 'EAN13',               -- CODE128 | CODE39 | EAN13 | EAN8 | ITF14",
                "  p_show_text => TRUE);                 -- human-readable number below the bars",
            ]),
        ],
    },
    {
        'id': "meta", 'n': "09",
        'titulo': ("Metadados e configuração", "Metadata and configuration"),
        'curto': ("Metadados", "Metadata"),
        'blocos': [
            ('tabela', [
                (("SetTitle / SetSubject / SetAuthor / SetKeywords / SetCreator",
                  "SetTitle / SetSubject / SetAuthor / SetKeywords / SetCreator"),
                 ("Metadados do documento",
                  "Document metadata")),
                (("SetDisplayMode(zoom, layout)",
                  "SetDisplayMode(zoom, layout)"),
                 ("Como o leitor abre o PDF",
                  "How the reader opens the PDF")),
                (("SetCompression(bool)",
                  "SetCompression(bool)"),
                 ("Compressão do conteúdo",
                  "Content compression")),
                (("SetDocumentConfig(json) · GetDocumentMetadata",
                  "SetDocumentConfig(json) · GetDocumentMetadata"),
                 ("Configuração em lote e leitura via JSON",
                  "Batch configuration and reading via JSON")),
                (("GetPageInfo(n)",
                  "GetPageInfo(n)"),
                 ("Dimensões e rotação de uma página (JSON)",
                  "Dimensions and rotation of a page (JSON)")),
            ]),
            ('janela', ("metadados.sql", "metadata.sql"), [
                "PL_FPDF.SetTitle('Relatório Mensal');",
                "PL_FPDF.SetAuthor('M&S do Brasil');",
                "PL_FPDF.SetDisplayMode(zoom => 'fullpage', layout => 'single');  -- como o leitor abre",
                "PL_FPDF.SetCompression(TRUE);",
                "-- ou tudo de uma vez:",
                "PL_FPDF.SetDocumentConfig(JSON_OBJECT_T('{\"title\":\"Relatório\",\"author\":\"M&S\"}'));",
            ], [
                "PL_FPDF.SetTitle('Monthly Report');",
                "PL_FPDF.SetAuthor('M&S do Brasil');",
                "PL_FPDF.SetDisplayMode(zoom => 'fullpage', layout => 'single');  -- how the reader opens it",
                "PL_FPDF.SetCompression(TRUE);",
                "-- or everything at once:",
                "PL_FPDF.SetDocumentConfig(JSON_OBJECT_T('{\"title\":\"Report\",\"author\":\"M&S\"}'));",
            ]),
        ],
    },
    {
        'id': "saida", 'n': "10",
        'titulo': ("Saída — gerar o PDF", "Output — producing the PDF"),
        'curto': ("Saída", "Output"),
        'blocos': [
            ('cabecalho', "Quando usar", "When to use it"),
            ('tabela', [
                (("OutputBlob → BLOB",
                  "OutputBlob → BLOB"),
                 ("Padrão: gravar em tabela, e-mail, APEX, ORDS",
                  "The default: store in a table, e-mail, APEX, ORDS")),
                (("OutputFile(arquivo, directory)",
                  "OutputFile(file, directory)"),
                 ("Gravar num DIRECTORY Oracle",
                  "Write into an Oracle DIRECTORY")),
                (("ReturnBlob · Output",
                  "ReturnBlob · Output"),
                 ("Compatibilidade com código legado/FPDF clássico",
                  "Compatibility with legacy code / classic FPDF")),
            ]),
            ('janela', ("saida.sql", "output.sql"), [
                "l_pdf := PL_FPDF.OutputBlob();                        -- BLOB para tabela/e-mail/APEX",
                "PL_FPDF.OutputFile(",
                "  p_filename  => 'relatorio.pdf',",
                "  p_directory => 'PDF_DIR');                           -- DIRECTORY Oracle com permissão de escrita",
            ], [
                "l_pdf := PL_FPDF.OutputBlob();                        -- BLOB for a table/e-mail/APEX",
                "PL_FPDF.OutputFile(",
                "  p_filename  => 'report.pdf',",
                "  p_directory => 'PDF_DIR');                           -- Oracle DIRECTORY with write permission",
            ]),
        ],
    },
    {
        'id': "manip", 'n': "11",
        'titulo': ("Manipulação de PDF existente", "Editing an existing PDF"),
        'curto': ("Manipular PDF", "Editing PDF"),
        'blocos': [
            ("desc",
             "Fluxo: <code>LoadPDF</code> → inspecionar/modificar → <code>OutputModifiedPDF</code>.",
             "The flow: <code>LoadPDF</code> → inspect/modify → <code>OutputModifiedPDF</code>."),
            ('tabela', [
                (("LoadPDF(blob)",
                  "LoadPDF(blob)"),
                 ("Carrega e interpreta um PDF existente",
                  "Loads and parses an existing PDF")),
                (("GetPageCount · GetPDFInfo",
                  "GetPageCount · GetPDFInfo"),
                 ("Total de páginas · metadados/versão (JSON)",
                  "Page total · metadata/version (JSON)")),
                (("RotatePage(n, graus) · RemovePage(n)",
                  "RotatePage(n, degrees) · RemovePage(n)"),
                 ("Rotação 0/90/180/270 · remoção de página",
                  "Rotation 0/90/180/270 · page removal")),
                (("AddWatermark(texto, opacidade, rotação, páginas, fonte, tam, cor)",
                  "AddWatermark(text, opacity, rotation, pages, font, size, colour)"),
                 ("Marca d'água em 'ALL' ou '1,3-5'",
                  "Watermark on 'ALL' or '1,3-5'")),
                (("GetWatermarks · GetActivePageCount · IsPageRemoved · IsPDFModified",
                  "GetWatermarks · GetActivePageCount · IsPageRemoved · IsPDFModified"),
                 ("Consultas de estado (JSON)",
                  "State queries (JSON)")),
                (("OutputModifiedPDF → BLOB · ClearPDFCache",
                  "OutputModifiedPDF → BLOB · ClearPDFCache"),
                 ("Gera o PDF final · libera memória",
                  "Produces the final PDF · frees memory")),
            ]),
            ('janela', ("editar.sql", "edit.sql"), [
                "PL_FPDF.LoadPDF(l_pdf);",
                "PL_FPDF.RotatePage(p_page_number => 1, p_rotation => 90);  -- 0/90/180/270",
                "PL_FPDF.AddWatermark(",
                "  p_text     => 'CONFIDENCIAL',",
                "  p_opacity  => 0.3,      -- 0.0 transparente … 1.0 opaco",
                "  p_rotation => 45,       -- diagonal clássica",
                "  p_pages    => 'ALL',    -- ou '1,3-5'",
                "  p_size     => 48,       -- pontos",
                "  p_color    => 'gray');",
                "PL_FPDF.RemovePage(3);",
                "l_pdf := PL_FPDF.OutputModifiedPDF();",
            ], [
                "PL_FPDF.LoadPDF(l_pdf);",
                "PL_FPDF.RotatePage(p_page_number => 1, p_rotation => 90);  -- 0/90/180/270",
                "PL_FPDF.AddWatermark(",
                "  p_text     => 'CONFIDENTIAL',",
                "  p_opacity  => 0.3,      -- 0.0 transparent … 1.0 opaque",
                "  p_rotation => 45,       -- the classic diagonal",
                "  p_pages    => 'ALL',    -- or '1,3-5'",
                "  p_size     => 48,       -- points",
                "  p_color    => 'gray');",
                "PL_FPDF.RemovePage(3);",
                "l_pdf := PL_FPDF.OutputModifiedPDF();",
            ]),
        ],
    },
    {
        'id': "overlay", 'n': "12",
        'titulo': ("Overlays — conteúdo sobre PDF existente", "Overlays — content on top of an existing PDF"),
        'curto': ("Overlays", "Overlays"),
        'blocos': [
            ("desc",
             "Carimbos, logos e assinaturas em coordenadas exatas (pontos PDF; Y de baixo para cima).",
             "Stamps, logos and sign-off marks at exact coordinates (PDF points; Y counts upwards)."),
            ('tabela', [
                (("OverlayText(página, texto, x, y, opções)",
                  "OverlayText(page, text, x, y, options)"),
                 ("Opções JSON: font, fontSize, color, opacity, rotation, align, bold, zOrder",
                  "JSON options: font, fontSize, color, opacity, rotation, align, bold, zOrder")),
                (("OverlayImage(página, blob, x, y, w, h, opções)",
                  "OverlayImage(page, blob, x, y, w, h, options)"),
                 ("JPEG/PNG; opacity, rotation, maintainAspect, scaleToFit",
                  "JPEG/PNG; opacity, rotation, maintainAspect, scaleToFit")),
                (("GetOverlays(página) · RemoveOverlay(id) · ClearOverlays(página)",
                  "GetOverlays(page) · RemoveOverlay(id) · ClearOverlays(page)"),
                 ("Gestão das sobreposições",
                  "Management of the overlays")),
            ]),
            ('janela', ("overlay.sql", "overlay.sql"), [
                "PL_FPDF.OverlayText(",
                "  p_page_number => 1,",
                "  p_text        => 'APROVADO',",
                "  p_x => 400, p_y => 700,               -- pontos PDF; Y conta de baixo para cima",
                "  p_options     => JSON_OBJECT_T('{",
                "    \"fontSize\":24, \"color\":\"FF0000\", \"opacity\":0.8,",
                "    \"rotation\":0, \"align\":\"left\", \"bold\":true }'));",
                "",
                "PL_FPDF.OverlayImage(",
                "  p_page_number => 1, p_image_blob => l_logo,",
                "  p_x => 450, p_y => 750,",
                "  p_width => 100, p_height => NULL,      -- NULL = proporcional / original",
                "  p_options => JSON_OBJECT_T('{\"opacity\":0.9,\"maintainAspect\":true}'));",
            ], [
                "PL_FPDF.OverlayText(",
                "  p_page_number => 1,",
                "  p_text        => 'APPROVED',",
                "  p_x => 400, p_y => 700,               -- PDF points; Y counts from the bottom up",
                "  p_options     => JSON_OBJECT_T('{",
                "    \"fontSize\":24, \"color\":\"FF0000\", \"opacity\":0.8,",
                "    \"rotation\":0, \"align\":\"left\", \"bold\":true }'));",
                "",
                "PL_FPDF.OverlayImage(",
                "  p_page_number => 1, p_image_blob => l_logo,",
                "  p_x => 450, p_y => 750,",
                "  p_width => 100, p_height => NULL,      -- NULL = proportional / original",
                "  p_options => JSON_OBJECT_T('{\"opacity\":0.9,\"maintainAspect\":true}'));",
            ]),
        ],
    },
    {
        'id': "multi", 'n': "13",
        'titulo': ("Multi-PDF: merge, split e extração", "Multi-PDF: merge, split and extraction"),
        'curto': ("Merge / Split", "Merge / Split"),
        'blocos': [
            ('tabela', [
                (("LoadPDFWithID(blob, id) · UnloadPDF(id) · GetLoadedPDFs",
                  "LoadPDFWithID(blob, id) · UnloadPDF(id) · GetLoadedPDFs"),
                 ("Vários PDFs em memória, cada um com ID",
                  "Several PDFs in memory, each with an ID")),
                (("MergePDFs(ids JSON) → BLOB",
                  "MergePDFs(ids JSON) → BLOB"),
                 ("Mescla na ordem do array",
                  "Merges in the order of the array")),
                (("SplitPDF(id, ranges JSON) → JSON",
                  "SplitPDF(id, ranges JSON) → JSON"),
                 ("Divide por intervalos (\"1-10\", \"11-20\", \"21-\")",
                  "Splits by range (\"1-10\", \"11-20\", \"21-\")")),
                (("ExtractPages(id, '1,5-10,15') → BLOB",
                  "ExtractPages(id, '1,5-10,15') → BLOB"),
                 ("Novo PDF só com as páginas indicadas",
                  "A new PDF with only the pages given")),
            ]),
            ('janela', ("merge.sql", "merge.sql"), [
                "PL_FPDF.LoadPDFWithID(l_capa, 'capa');",
                "PL_FPDF.LoadPDFWithID(l_corpo, 'corpo');",
                "l_final := PL_FPDF.MergePDFs(JSON_ARRAY_T('[\"capa\",\"corpo\"]'));",
            ], [
                "PL_FPDF.LoadPDFWithID(l_cover, 'cover');",
                "PL_FPDF.LoadPDFWithID(l_body, 'body');",
                "l_final := PL_FPDF.MergePDFs(JSON_ARRAY_T('[\"cover\",\"body\"]'));",
            ]),
        ],
    },
    {
        'id': "seguranca", 'n': "14",
        'titulo': ("Segurança e criptografia (v3.2)", "Security and encryption (v3.2)"),
        'curto': ("Segurança", "Security"),
        'blocos': [
            ('tabela', [
                (("EncryptPDF(pdf, senha_user, senha_owner, permissões, algoritmo)",
                  "EncryptPDF(pdf, user_password, owner_password, permissions, algorithm)"),
                 ("Protege um BLOB pronto — 'AES-256', 'AES-128', 'RC4-128' ou 'RC4-40'",
                  "Protects a finished BLOB — 'AES-256', 'AES-128', 'RC4-128' or 'RC4-40'")),
                (("DecryptPDF(pdf, senha)",
                  "DecryptPDF(pdf, password)"),
                 ("Remove a proteção",
                  "Removes the protection")),
                (("IsEncrypted(pdf) · GetSecurityInfo(pdf)",
                  "IsEncrypted(pdf) · GetSecurityInfo(pdf)"),
                 ("Verifica e inspeciona (algoritmo, chave, permissões)",
                  "Checks and inspects (algorithm, key, permissions)")),
                (("SetEncryption(...) · SetPermissions(...)",
                  "SetEncryption(...) · SetPermissions(...)"),
                 ("Criptografia e permissões de um documento novo, antes do OutputBlob",
                  "Encryption and permissions for a new document, before OutputBlob")),
                (("SetPDFVersion('1.7') · GetPDFVersion",
                  "SetPDFVersion('1.7') · GetPDFVersion"),
                 ("Versão do arquivo gerado",
                  "Version of the generated file")),
            ]),
            ('janela', ("proteger.sql", "protect.sql"), [
                "l_perms := JSON_OBJECT_T();",
                "l_perms.put('print', TRUE);          -- também: modify, copy, annotate,",
                "l_perms.put('copy',  FALSE);         --   fill_forms, extract, assemble, print_high",
                "",
                "l_seguro := PL_FPDF.EncryptPDF(",
                "  p_pdf            => l_pdf,",
                "  p_user_password  => 'senhaLeitura',   -- pedida ao abrir",
                "  p_owner_password => 'senhaAdmin',     -- NULL = igual à de usuário",
                "  p_permissions    => l_perms,",
                "  p_encryption     => 'AES-256');      -- ou 'AES-128', 'RC4-128', 'RC4-40'",
            ], [
                "l_perms := JSON_OBJECT_T();",
                "l_perms.put('print', TRUE);          -- also: modify, copy, annotate,",
                "l_perms.put('copy',  FALSE);         --   fill_forms, extract, assemble, print_high",
                "",
                "l_seguro := PL_FPDF.EncryptPDF(",
                "  p_pdf            => l_pdf,",
                "  p_user_password  => 'readPassword',   -- asked for on opening",
                "  p_owner_password => 'adminPassword',  -- NULL = same as the user one",
                "  p_permissions    => l_perms,",
                "  p_encryption     => 'AES-256');      -- or 'AES-128', 'RC4-128', 'RC4-40'",
            ]),
            ("nota",
             "<b>Senha não é assinatura.</b> A criptografia acima protege o arquivo\n  (quem abre, quem imprime, quem copia) — ela não atesta autoria nem detecta adulteração.\n  <b>Assinatura digital</b> (PAdES, certificado ICP-Brasil) ainda não existe na biblioteca.",
             "<b>A password is not a signature.</b> The encryption above protects the file\n  (who opens it, who prints it, who copies from it) — it does not attest authorship nor detect\n  tampering. <b>Digital signatures</b> (PAdES, ICP-Brasil certificates) do not exist in the\n  library yet."),
        ],
    },
]
